var products = [{
    "id": 0,
    "title": "-- Select Anyone --",
    "price": "",
    "description": "",
    "brand": "",
    "image": "im./images/charcoal/1.png",
  },
// ARMANI PERFUME. DATA 
  {
    "id": 1,
    "title": "Sky di Gioia",
    "price": "1999 PKR",
    "description": "Armani perfumes exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "Armani",
    "image": "./images/perfume/armani1.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "FREGNANCE",
  },
  {
    "id": 2,
    "title": "Acqua di Gioia",
    "price": "1199 PKR",
    "description": "Armani perfumes exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "Armani",
    "image": "./images/perfume/armani2.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "FREGNANCE",
  },
  {
    "id": 3,
    "title": "Armani Mania",
    "price": "1399 PKR",
    "description": "Armani perfumes exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "Armani",
    "image": "./images/perfume/armani3.png",
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "FREGNANCE",
  },
  {
    "id": 4,
    "title": "Armani Prive",
    "price": "1999 PKR",
    "description": "Armani perfumes exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "Armani",
    "image": "./images/perfume/armani4.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "FREGNANCE",
},
// chanel perfume 
  {
    "id": 5,
    "title": "BLEU DE CHANEL",
    "price": "1499 PKR",
    "description": "Chanel brand perfumes epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "CHANEL",
    "image": "./images/perfume/chanel1.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "FREGNANCE",
},
  {
    "id": 6,
    "title": "COCO MADEMOISELLE",
    "price": "1399 PKR",
    "description": "Chanel brand perfumes epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "CHANEL",
  "image": "./images/perfume/channel2.png",
        "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "FREGNANCE",
},
  {
    "id": 7,
    "title": "SYCOMORE",
    "price": "1299 PKR",
    "description": "Chanel brand perfumes epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "CHANEL",
    "image": "./images/perfume/channel3.png",
        "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "FREGNANCE",
},
  {
    "id": 8,
    "title": "COCO NOIR",
    "price": "2399 PKR",
    "description": "Chanel brand perfumes epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "CHANEL",
    "image": "./images/perfume/channel4.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "FREGNANCE",
},
// dior perfume 
  {
    "id": 9,
    "title": "DIOR ADDICT",
    "price": "2999 PKR",
    "description": "Dior perfumes exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "DIOR",
    "image":" ./images/perfume/dior1.png",    
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "FREGNANCE",
},
  {
    "id": 10,
    "title": "JOY DIOR",
    "price": "2550 PKR",
    "description": "Dior perfumes exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "DIOR",
    "image": "./images/perfume/dior2.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "FREGNANCE",
},
  {
    "id": 11,
    "title": "JADORE",
    "price": "1850 PKR",
    "description": "Dior perfumes exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "DIOR",
    "image": "./images/perfume/dior3.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "FREGNANCE",
},
  {
    "id": 12,
    "title": "SAUVAGE",
    "price": "999 PKR",
    "description": "Dior perfumes exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "DIOR",
    "image": "./images/perfume/dior4.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "FREGNANCE",
},
// herme perfumes 
  {
    "id": 13,
    "title": "UN JARDIN EN MEDITERRENEE",
    "price": "1200 PKR",
    "description": "Hermes perfumes epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "Hermes",
    "image": "./images/perfume/hermes1.png",
        "size": "Large & Small",
    "arrival": "Yes",
    "material": "FREGNANCE",
},
  {
    "id": 14,
    "title": "JOUR d'HERMES",
    "price": "999 PKR",
    "description": "Hermes perfumes epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "Hermes",
    "image": "./images/perfume/hermes2.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "FREGNANCE",
},
  {
    "id": 15,
    "title": "TERRE D'HERMES",
    "price": "1299 PKR",
    "description": "Hermes perfumes epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "Hermes",
    "image": "./images/perfume/hermes3.png",
        "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "FREGNANCE",
},
  {
    "id": 16,
    "title": "KELLY CALECHE",
    "price": "1599 PKR",
    "description": "Hermes perfumes epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "Hermes",
    "image": "./images/perfume/hermes4.png",
    "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "FREGNANCE",
},
// mont black perfumes  
{
  "id": 17,
  "title": "STARWALKER",
  "price": "1599 PKR",
  "description": "Mont Blanc perfumes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "Mont Blanc",
  "image": "./images/perfume/mont blanc1.jpg",
  "size": "Large & Small & Medium",
  "arrival": "No",
  "material": "FREGNANCE",
},
{
  "id": 18,
  "title": "SIGNATURE",
  "price": "1599 PKR",
  "description": "Mont Blanc perfumes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "Mont Blanc",
  "image": "./images/perfume/mont blanc 2.png",
  "size": "Large & Small & Medium",
  "arrival": "No",
  "material": "FREGNANCE",
},
{
  "id": 19,
  "title": "LEGEND BLUE",
  "price": "1599 PKR",
  "description": "Mont Blanc perfumes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "Mont Blanc",
  "image": "./images/perfume/mont blanc3.png",
  "size": "Large & Small & Medium",
  "arrival": "No",
  "material": "FREGNANCE",
},
{
  "id": 20,
  "title": "LEGEND BLACK",
  "price": "1599 PKR",
  "description": "Mont Blanc perfumes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "Mont Blanc",
  "image": "./images/perfume/mont blanc 4.png",
  "size": "Large & Small & Medium",
  "arrival": "No",
  "material": "FREGNANCE",
},
]
