var products = [{
    "id": 0,
    "title": "-- Select Anyone --",
    "price": "",
    "description": "",
    "brand": "",
    "image": "im./images/charcoal/1.png",
  },
// CK WAtches DATA 
  {
    "id": 1,
    "title": "Checkered Chunkies",
    "price": "1999 PKR",
    "description": "CALVIN KELIN Watchs are exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "CALVIN KELIN",
    "image": "./images/shoes/CK/1.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Metal And Leather",
  },
  {
    "id": 2,
    "title": "Chunky Sneakers",
    "price": "1199 PKR",
    "description": "CALVIN KELIN Watchs are exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "CALVIN KELIN",
    "image": "./images/shoes/CK/2.png",
    "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
  },
  {
    "id": 3,
    "title": "Stealth Chunky Sneakers",
    "price": "1399 PKR",
    "description": "CALVIN KELIN Watchs are exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "CALVIN KELIN",
    "image": "./images/shoes/CK/3.png",
    "size": "ALL Sizes",
    "arrival": "Yes",
    "material": "Metal And Leather",
  },
  {
    "id": 4,
    "title": "Chunky Trainers",
    "price": "1999 PKR",
    "description": "CALVIN KELIN Watchs are exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "CALVIN KELIN",
    "image": "./images/shoes/CK/4.png",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
// JORDAN 
  {
    "id": 5,
    "title": "Eclipse Midnight Edition",
    "price": "1499 PKR",
    "description": "ROLEX Brand Watches are epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "ROLEX",
    "image": "./images/shoes/jordan/1.png",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
  {
    "id": 6,
    "title": "Nightfire Retro HighTops",
    "price": "1399 PKR",
    "description": "ROLEX Brand Watches are epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "ROLEX",
  "image": "./images/shoes/jordan/J.3.jpg",
        "size": "ALL Sizes ",
    "arrival": "Yes",
    "material": "Metal And Leather",
},
  {
    "id": 7,
    "title": "Sandstorm Lowtops",
    "price": "1299 PKR",
    "description": "ROLEX Brand Watches are epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "ROLEX",
    "image": "./images/shoes/jordan/3.png",
        "size": "ALL Sizes ",
    "arrival": "Yes",
    "material": "Metal And Leather",
},
  {
    "id": 8,
    "title": "Frost Retro High-Tops",
    "price": "2399 PKR",
    "description": "ROLEX Brand Watches are epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "ROLEX",
    "image": "./images/shoes/jordan/J.2.jpg",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
// FILA 
  {
    "id": 9,
    "title": "Chromatic White Sneakers",
    "price": "2999 PKR",
    "description": "louis vuition Watches exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "VL",
    "image":" ./images/shoes/Fila/1.jpg",    
    "size": "ALL Sizes",
    "arrival": "Yes",
    "material": "Metal And Leather",
},
  {
    "id": 10,
    "title": "Blaze Chunkies",
    "price": "2550 PKR",
    "description": "louis vuition Watches exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "VL",
    "image": "./images/shoes/Fila/2.png",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
  {
    "id": 11,
    "title": "Fusion Chroma",
    "price": "1850 PKR",
    "description": "louis vuition Watches exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "VL",
    "image": "./images/shoes/Fila/F.1.jpg",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
  {
    "id": 12,
    "title": "Shadowfire Sneakers",
    "price": "999 PKR",
    "description": "louis vuition Watches exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "VL",
    "image": "./images/shoes/Fila/F.2.jpg",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
// LEVIS
  {
    "id": 13,
    "title": "UrbanEdge Sneakers",
    "price": "1200 PKR",
    "description": "Cartier Watches epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "LEVIS",
    "image": "./images/shoes/Levis/1.jpg",
        "size": "ALL Sizes",
    "arrival": "Yes",
    "material": "Metal And Leather",
},
  {
    "id": 14,
    "title": "StreetCraft Sneakers",
    "price": "999 PKR",
    "description": "Cartier Watches epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "LEVIS",
    "image": "./images/shoes/Levis/2.jpg",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
  {
    "id": 15,
    "title": "ModaStride Sneakers",
    "price": "1299 PKR",
    "description": "Cartier Watches epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "LEVIS",
    "image": "./images/shoes/Levis/3.png",
        "size": "ALL Sizes ",
    "arrival": "No",
    "material": "Metal And Leather",
},
  {
    "id": 16,
    "title": "ModaStride Sneakers",
    "price": "1599 PKR",
    "description": "Cartier Watches epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "LEVIS",
    "image": "./images/shoes/Levis/4.jpg",
    "size": "ALL Sizes ",
    "arrival": "No",
    "material": "Metal And Leather",
},
// SKECHERS  
{
  "id": 17,
  "title": "Shadow Stride",
  "price": "1599 PKR",
  "description": "Hemilton Wathes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "HEMILTON",
  "image": "./images/shoes/sketchers/1.jpg",
  "size": "ALL Sizes ",
  "arrival": "No",
  "material": "Metal And Leather",
},
{
  "id": 18,
  "title": "Metro Stride",
  "price": "1599 PKR",
  "description": "Hemilton Wathes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "HEMILTON",
  "image": "./images/shoes/sketchers/2.png",
  "size": "ALL Sizes ",
  "arrival": "No",
  "material": "Metal And Leather",
},
{
  "id": 19,
  "title": "UrbanMist Chunkies",
  "price": "1599 PKR",
  "description": "Hemilton Wathes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "HEMILTON",
  "image": "./images/shoes/sketchers/3.jpg",
  "size": "ALL Sizes ",
  "arrival": "No",
  "material": "Metal And Leather",
},
{
  "id": 20,
  "title": "LunarGlide Chunkies",
  "price": "1599 PKR",
  "description": "Hemilton Wathes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "HEMILTON",
  "image": "./images/shoes/sketchers/4.jpg",
  "size": "ALL Sizes ",
  "arrival": "No",
  "material": "Metal And Leather",
},
]
