var products = [{
    "id": 0,
    "title": "-- Select Anyone --",
    "price": "",
    "description": "",
    "brand": "",
    "image": "im./images/charcoal/1.png",
  },
// Ck wallet. DATA 
  {
    "id": 1,
    "title": "Crossbody Bag",
    "price": "1999 PKR",
    "description": "CK Wallets and Bags offers timeless elegance with premium craftsmanship, featuring sleek designs and durable materials for everyday sophistication.",
    "brand": "CK",
    "image": "./images/wallets/ck1.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Leather",
  },
  {
    "id": 2,
    "title": "Crossbody Bag",
    "price": "1199 PKR",
    "description": "CK Wallets and Bags offers timeless elegance with premium craftsmanship, featuring sleek designs and durable materials for everyday sophistication.",
    "brand": "CK",
    "image": "./images/wallets/ck2.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Leather",
  },
  {
    "id": 3,
    "title": "Shoulder bag",
    "price": "1399 PKR",
    "description": "CK Wallets and Bags offers timeless elegance with premium craftsmanship, featuring sleek designs and durable materials for everyday sophistication.",
    "brand": "CK",
    "image": "./images/wallets/ck3.png",
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Leather",
  },
  {
    "id": 4,
    "title": "Logo Jacquard Bag",
    "price": "1999 PKR",
    "description": "CK Wallets and Bags offers timeless elegance with premium craftsmanship, featuring sleek designs and durable materials for everyday sophistication.",
    "brand": "CK",
    "image": "./images/wallets/ck4.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Leather",
},
// chanel wallet 
  {
    "id": 5,
    "title": "VANITY CASE",
    "price": "1499 PKR",
    "description": "Chanel wallets and bags epitomize luxury and style with iconic designs, exquisite craftsmanship, and timeless elegance for discerning fashion enthusiasts",
    "brand": "CHANEL",
    "image": "./images/wallets/chanel1.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Leather",
},
  {
    "id": 6,
    "title": "MINI SHOPPING BAG",
    "price": "1399 PKR",
    "description": "Chanel wallets and bags epitomize luxury and style with iconic designs, exquisite craftsmanship, and timeless elegance for discerning fashion enthusiasts",
    "brand": "CHANEL",
  "image": "./images/wallets/chanel2.png",
        "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Leather",
},
  {
    "id": 7,
    "title": "LARGE HOBO BAG",
    "price": "1299 PKR",
    "description": "Chanel wallets and bags epitomize luxury and style with iconic designs, exquisite craftsmanship, and timeless elegance for discerning fashion enthusiasts",
    "brand": "CHANEL",
    "image": "./images/wallets/chanel3.png",
        "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Leather",
},
  {
    "id": 8,
    "title": "BAG WITH TOP HANDLE",
    "price": "2399 PKR",
    "description": "Chanel wallets and bags epitomize luxury and style with iconic designs, exquisite craftsmanship, and timeless elegance for discerning fashion enthusiasts",
    "brand": "CHANEL",
    "image": "./images/wallets/chanel4png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Leather",
},
// dior data 
  {
    "id": 9,
    "title": "Large C'est Dior Bag",
    "price": "2999 PKR",
    "description": "Dior brand wallets and bags epitomize luxury and sophistication, featuring iconic designs and impeccable craftsmanship for timeless elegance and style",
    "brand": "DIOR",
    "image":" ./images/wallets/dior1.png",    
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Leather",
},
  {
    "id": 10,
    "title": " Dior Top Handle Bag",
    "price": "2550 PKR",
    "description": "Dior brand wallets and bags epitomize luxury and sophistication, featuring iconic designs and impeccable craftsmanship for timeless elegance and style",
    "brand": "DIOR",
    "image": "./images/wallets/dior2.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Leather",
},
  {
    "id": 11,
    "title": " Saddle Bag with Strap",
    "price": "1850 PKR",
    "description": "Dior brand wallets and bags epitomize luxury and sophistication, featuring iconic designs and impeccable craftsmanship for timeless elegance and style",
    "brand": "DIOR",
    "image": "./images/wallets/dior3.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Leather",
},
  {
    "id": 12,
    "title": "Small Lady D-Joy Bag",
    "price": "999 PKR",
    "description": "Dior brand wallets and bags epitomize luxury and sophistication, featuring iconic designs and impeccable craftsmanship for timeless elegance and style",
    "brand": "DIOR",
    "image": "./images/wallets/dior4.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Leather",
},
// gucci data 
  {
    "id": 13,
    "title": "GUCCI HORSEBIT 1955 MINI SHOULDER BAG",
    "price": "1200 PKR",
    "description": "Gucci brand wallets and bags epitomize luxury and sophistication, showcasing iconic designs and impeccable craftsmanship for timeless elegance and unparalleled style.",
    "brand": "GUCCI",
    "image": "./images/wallets/gucci1.png",
        "size": "Large & Small",
    "arrival": "Yes",
    "material": "Leather",
},
  {
    "id": 14,
    "title": "MEDIUM GG RIPSTOP CROSSBODY BAG",
    "price": "999 PKR",
    "description": "Gucci brand wallets and bags epitomize luxury and sophistication, showcasing iconic designs and impeccable craftsmanship for timeless elegance and unparalleled style.",
    "brand": "GUCCI",
    "image": "./images/wallets/gucci2.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Leather",
},
  {
    "id": 15,
    "title": "GUCCI HORSEBIT 1955 MINI BAG",
    "price": "1299 PKR",
    "description": "Gucci brand wallets and bags epitomize luxury and sophistication, showcasing iconic designs and impeccable craftsmanship for timeless elegance and unparalleled style.",
    "brand": "GUCCI",
    "image": "./images/wallets/gucci 3.png",
        "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Leather",
},
  {
    "id": 16,
    "title": "OPHIDIA GG MINI WALLET",
    "price": "1599 PKR",
    "description": "Gucci brand wallets and bags epitomize luxury and sophistication, showcasing iconic designs and impeccable craftsmanship for timeless elegance and unparalleled style.",
    "brand": "GUCCI",
    "image": "./images/wallets/gucci 4.png",
    "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Leather",
},
// ysl data 
{
  "id": 17,
  "title": "SUNSET MEDIUM IN SMOOTH LEATHER",
  "price": "1599 PKR",
  "description": "YSL brand wallets and bags epitomize luxury and sophistication, showcasing iconic designs and impeccable craftsmanship for timeless elegance and unparalleled style.",
  "brand": "VSL",
  "image": "./images/wallets/sl1.png",
  "size": "Large & Small & Medium",
  "arrival": "No",
  "material": "Leather",
},
{
  "id": 18,
  "title": "JAMIE 4.3 SMALL IN LAMBSKIN",
  "price": "1599 PKR",
  "description": "YSL brand wallets and bags epitomize luxury and sophistication, showcasing iconic designs and impeccable craftsmanship for timeless elegance and unparalleled style.",
  "brand": "VSL",
  "image": "./images/wallets/sl2.png",
  "size": "Large & Small & Medium",
  "arrival": "No",
  "material": "Leather",
},
{
  "id": 19,
  "title": "KATE SMALL IN PATENT LEATHERF",
  "price": "1599 PKR",
  "description": "YSL brand wallets and bags epitomize luxury and sophistication, showcasing iconic designs and impeccable craftsmanship for timeless elegance and unparalleled style.",
  "brand": "VSL",
  "image": "./images/wallets/sl3.png",
  "size": "Large & Small & Medium",
  "arrival": "No",
  "material": "Leather",
},
{
  "id": 20,
  "title": "CASSANDRE MATELASSÉ ENVELOPE WALLET",
  "price": "1599 PKR",
  "description": "YSL brand wallets and bags epitomize luxury and sophistication, showcasing iconic designs and impeccable craftsmanship for timeless elegance and unparalleled style.",
  "brand": "VSL",
  "image": "./images/wallets/sl4.png",
  "size": "Large & Small & Medium",
  "arrival": "No",
  "material": "Leather",
},
]
