var products = [{
    "id": 0,
    "title": "-- Select Anyone --",
    "price": "",
    "description": "",
    "brand": "",
    "image": "im./images/charcoal/1.png",
  },
// CK WAtches DATA 
  {
    "id": 1,
    "title": "Bracelet Watch",
    "price": "1999 PKR",
    "description": "CALVIN KELIN Watchs are exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "CALVIN KELIN",
    "image": "./images/Watches/CK/1.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Metal And Leather",
  },
  {
    "id": 2,
    "title": "Bracelet 3-Hand Watch",
    "price": "1199 PKR",
    "description": "CALVIN KELIN Watchs are exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "CALVIN KELIN",
    "image": "./images/Watches/CK/2.png",
    "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
  },
  {
    "id": 3,
    "title": "Leather Strap Watch",
    "price": "1399 PKR",
    "description": "CALVIN KELIN Watchs are exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "CALVIN KELIN",
    "image": "./images/Watches/CK/3.png",
    "size": "ALL Sizes",
    "arrival": "Yes",
    "material": "Metal And Leather",
  },
  {
    "id": 4,
    "title": "Leather Strap",
    "price": "1999 PKR",
    "description": "CALVIN KELIN Watchs are exude sophistication and allure, offering a captivating blend of scents that evoke elegance and luxury for discerning individuals.",
    "brand": "CALVIN KELIN",
    "image": "./images/Watches/CK/4.png",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
// Rolex perfume 
  {
    "id": 5,
    "title": "Cosmograph Daytona",
    "price": "1499 PKR",
    "description": "ROLEX Brand Watches are epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "ROLEX",
    "image": "./images/Watches/Rolex/1.png",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
  {
    "id": 6,
    "title": "Sky-Dweller",
    "price": "1399 PKR",
    "description": "ROLEX Brand Watches are epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "ROLEX",
  "image": "./images/Watches/Rolex/2.png",
        "size": "ALL Sizes ",
    "arrival": "Yes",
    "material": "Metal And Leather",
},
  {
    "id": 7,
    "title": "Yacht-Master 42",
    "price": "1299 PKR",
    "description": "ROLEX Brand Watches are epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "ROLEX",
    "image": "./images/Watches/Rolex/3.png",
        "size": "ALL Sizes ",
    "arrival": "Yes",
    "material": "Metal And Leather",
},
  {
    "id": 8,
    "title": "Submariner Date",
    "price": "2399 PKR",
    "description": "ROLEX Brand Watches are epitomize sophistication and allure, presenting captivating scents evoking elegance and luxury for discerning individuals",
    "brand": "ROLEX",
    "image": "./images/Watches/Rolex/r--4.png",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
// VL 
  {
    "id": 9,
    "title": "  Tambour Street Diver",
    "price": "2999 PKR",
    "description": "louis vuition Watches exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "VL",
    "image":" ./images/Watches/louis vuition/louis1.png",    
    "size": "ALL Sizes",
    "arrival": "Yes",
    "material": "Metal And Leather",
},
  {
    "id": 10,
    "title": "Voyager Skeleton",
    "price": "2550 PKR",
    "description": "louis vuition Watches exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "VL",
    "image": "./images/Watches/louis vuition/louis.2.png",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
  {
    "id": 11,
    "title": "Tambour Twenty",
    "price": "1850 PKR",
    "description": "louis vuition Watches exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "VL",
    "image": "./images/Watches/louis vuition/louis3.jpg",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
  {
    "id": 12,
    "title": "Tambour Street Diver",
    "price": "999 PKR",
    "description": "louis vuition Watches exude sophistication with captivating scents that evoke elegance, allure, and luxury, embodying timeless beauty for discerning fragrance enthusiasts",
    "brand": "VL",
    "image": "./images/Watches/louis vuition/louis4.png",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
// CAITIER
  {
    "id": 13,
    "title": "BALLON BLEU DE",
    "price": "1200 PKR",
    "description": "Cartier Watches epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "CARTIER",
    "image": "./images/Watches/cartier/cartier1.png",
        "size": "ALL Sizes",
    "arrival": "Yes",
    "material": "Metal And Leather",
},
  {
    "id": 14,
    "title": "RONDE MUST DE",
    "price": "999 PKR",
    "description": "Cartier Watches epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "CARTIER",
    "image": "./images/Watches/cartier/cartier2.png",
        "size": "ALL Sizes",
    "arrival": "No",
    "material": "Metal And Leather",
},
  {
    "id": 15,
    "title": "PASHA DE BLACK",
    "price": "1299 PKR",
    "description": "Cartier Watches epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "CARTIER",
    "image": "./images/Watches/cartier/cartier3.png",
        "size": "ALL Sizes ",
    "arrival": "No",
    "material": "Metal And Leather",
},
  {
    "id": 16,
    "title": "PASHA DE SILVER",
    "price": "1599 PKR",
    "description": "Cartier Watches epitomize luxury, offering captivating scents that exude sophistication, style, and allure, reflecting the brand's timeless elegance and charm..",
    "brand": "CARTIER",
    "image": "./images/Watches/cartier/cartier 4.png",
    "size": "ALL Sizes ",
    "arrival": "No",
    "material": "Metal And Leather",
},
// HAMMILTION  
{
  "id": 17,
  "title": "JAZZMASTER AUTO CHRONO",
  "price": "1599 PKR",
  "description": "Hemilton Wathes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "HEMILTON",
  "image": "./images/Watches/hamilton/1.png",
  "size": "ALL Sizes ",
  "arrival": "No",
  "material": "Metal And Leather",
},
{
  "id": 18,
  "title": "PILOT AUTO GOLDEN BLACK",
  "price": "1599 PKR",
  "description": "Hemilton Wathes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "HEMILTON",
  "image": "./images/Watches/hamilton/2.png",
  "size": "ALL Sizes ",
  "arrival": "No",
  "material": "Metal And Leather",
},
{
  "id": 19,
  "title": "PILOT PIONEER BRONZE BLACK",
  "price": "1599 PKR",
  "description": "Hemilton Wathes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "HEMILTON",
  "image": "./images/Watches/hamilton/3.png",
  "size": "ALL Sizes ",
  "arrival": "No",
  "material": "Metal And Leather",
},
{
  "id": 20,
  "title": "AMERICAN CLASSIC INTRA-MATIC AUTO",
  "price": "1599 PKR",
  "description": "Hemilton Wathes embody sophistication with captivating scents, reflecting elegance and refinement, perfect for individuals who appreciate timeless luxury and style..",
  "brand": "HEMILTON",
  "image": "./images/Watches/hamilton/4.png",
  "size": "ALL Sizes ",
  "arrival": "No",
  "material": "Metal And Leather",
},
]
