var products = [{
    "id": 0,
    "title": "-- Select Anyone --",
    "price": "",
    "description": "",
    "brand": "",
    "image": "im./images/charcoal/1.png",
  },
// Almrah. DATA 
  {
    "id": 1,
    "title": "3 PIECE STITCHED",
    "price": "1999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 1.jpg",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Shefoun & loan Fabric",
  },
  {
    "id": 2,
    "title": "3 PIECE STITCHED",
    "price": "1199 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 2.jpg",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Shefoun & loan Fabric",
  },
  {
    "id": 3,
    "title": "3 PIECE STITCHED",
    "price": "1399 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 4.jpg",
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Shefoun & loan Fabric",
  },
  {
    "id": 4,
    "title": "3 PIECE STITCHED",
    "price": "1999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 3.jpg",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 5,
    "title": "3 PIECE STITCHED",
    "price": "1499 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 5.jpg",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 6,
    "title": "2 PIECE STITCHED",
    "price": "1399 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
  "image": "./images/Almirah/img 6.jpg",
        "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 7,
    "title": "2 PIECE STITCHED ",
    "price": "1299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 7.jpg",
        "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 8,
    "title": "3 PIECE STITCHED",
    "price": "2399 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 8.jpg",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 9,
    "title": "3 PIECE STITCHED",
    "price": "2999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image":" ./images/Almirah/img 9.jpg",    
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 10,
    "title": " 3 PIECE STITCHED",
    "price": "2550 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 10.jpg",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 11,
    "title": " 3 PIECE STITCHED",
    "price": "1850 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 11.jpg",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 12,
    "title": "2 PIECE STITCHED",
    "price": "999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 12.jpg",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 13,
    "title": "3 PIECE STITCHED",
    "price": "1200 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 13.jpg",
        "size": "Large & Small",
    "arrival": "Yes",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 14,
    "title": "2 PIECE STITCHED",
    "price": "999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 14.jpg",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 15,
    "title": "3 PIECE STITCHED",
    "price": "1299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 15.jpg",
        "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Shefoun & loan Fabric",
},
  {
    "id": 16,
    "title": "3 PIECE STITCHED",
    "price": "1599 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Almirah Collections Pakistan No 1 Brand",
    "brand": "CharCoal",
    "image": "./images/Almirah/img 16.jpg",
    "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Shefoun & loan Fabric",
},



]
