var products = [{
    "id": 0,
    "title": "-- Select Anyone --",
    "price": "",
    "description": "",
    "brand": "",
    "image": "im./images/charcoal/1.png",
  },
// J. DATA 
  {
    "id": 1,
    "title": "CASUAL COAT BROWN",
    "price": "9299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/1.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
  },
  {
    "id": 2,
    "title": "CASUAL COAT NAVY",
    "price": "11899 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/2.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
  },
  {
    "id": 3,
    "title": "CASUAL COAT NAVY",
    "price": "12399 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/3.png",
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Silk Fabric",
  },
  {
    "id": 4,
    "title": "CASUAL COAT MAROON",
    "price": "8499 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/4.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 5,
    "title": "CASUAL COAT BLUE",
    "price": "14999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/5.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 6,
    "title": "CASUAL COAT MAROON",
    "price": "13299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
  "image": "./images/charcoal/6.png",
        "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Silk Fabric",
},
  {
    "id": 7,
    "title": "CASUAL COAT MUSTARD ",
    "price": "12999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/7.png",
        "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Silk Fabric",
},
  {
    "id": 8,
    "title": "CASUAL COAT KHAKI",
    "price": "2399 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/8.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 9,
    "title": "CASUAL COAT KHAKI2",
    "price": "2999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image":" ./images/charcoal/9.png",    
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Silk Fabric",
},
  {
    "id": 10,
    "title": " CASUAL COAT KHAKI",
    "price": "5550 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/10.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 11,
    "title": " CASUAL COAT GREY",
    "price": "7850 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/11.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 12,
    "title": "CASUAL COAT NAVY",
    "price": "5999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/12.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 13,
    "title": "CASUAL COAT GREY",
    "price": "6599 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/13.png",
        "size": "Large & Small",
    "arrival": "Yes",
    "material": "Silk Fabric",
},
  {
    "id": 14,
    "title": "CASUAL COAT DARK",
    "price": "8999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/14.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 15,
    "title": "CASUAL COAT BLACK",
    "price": "12299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/15.png",
        "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 16,
    "title": "CASUAL COAT BLACK",
    "price": "12599 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Charcoal Collection of Casual Coats",
    "brand": "CharCoal",
    "image": "./images/charcoal/16.png",
    "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Cotton Fabric",
},



]
