var products = [{
    "id": 0,
    "title": "-- Select Anyone --",
    "price": "",
    "description": "",
    "brand": "",
    "image": "im./images/Hoodies/1.png",
  },
// J. DATA 
  {
    "id": 1,
    "title": "CHARCOAL FASHION SWEATSHIRT",
    "price": "999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/1.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
  },
  {
    "id": 2,
    "title": "RUST BASIC RAGLAN SWEAT SHIRT",
    "price": "1899 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/2.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
  },
  {
    "id": 3,
    "title": "BASIC MOCK NECK SWEAT SHIRT",
    "price": "2399 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/3.png",
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Silk Fabric",
  },
  {
    "id": 4,
    "title": "OFF WHITE BASIC HOODIE",
    "price": "2399 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/4.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 5,
    "title": "MULTI TIE-DYE HOODIE",
    "price": "4999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/5.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 6,
    "title": "GREEN BASIC HOODIE",
    "price": "1299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
  "image": "./images/Hoodies/6.png",
        "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Silk Fabric",
},
  {
    "id": 7,
    "title": "GREEN BASIC HOODIE ",
    "price": "1999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/7.png",
        "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Silk Fabric",
},
  {
    "id": 8,
    "title": "WHITE SWEATSHIRT",
    "price": "899 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/8.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 9,
    "title": "TIE-DYE SWEATSHIRT",
    "price": "999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image":" ./images/Hoodies/9.png",    
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Silk Fabric",
},
  {
    "id": 10,
    "title": " REGULAR SWEATSHIRT",
    "price": "550 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/10.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 11,
    "title": " KNIT SWEATSHIRT",
    "price": "780 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/11.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 12,
    "title": "MULTI SWEATSHIRT",
    "price": "999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/12.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 13,
    "title": "GREEN FASHION SWEATSHIRT",
    "price": "599 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/13.png",
        "size": "Large & Small",
    "arrival": "Yes",
    "material": "Silk Fabric",
},
  {
    "id": 14,
    "title": "MADDY GREEN SWEATSHIRT",
    "price": "999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/14.png",
        "size": "Large & Small",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 15,
    "title": "OFF WHITE PRINTED HOODIE",
    "price": "2299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/15.png",
        "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Silk Fabric",
},
  {
    "id": 16,
    "title": "OFF WHITE FASHION HOODIE",
    "price": "2599 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of Diners Collection of Sweatshirts and Printed Hoodies",
    "brand": "CharCoal",
    "image": "./images/Hoodies/16.png",
    "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Cotton Fabric",
},



]
