var products = [{
    "id": 0,
    "title": "-- Select Anyone --",
    "price": "",
    "description": "",
    "brand": "",
    "image": "images/No_Image.png",
  },
//   GUL AHMED DATA
  {
    "id": 1,
    "title": "Super Cool Fabric Cotton Blue",
    "price": "2299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/bkue1.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
  },
  {
    "id": 2,
    "title": "GUL 90000 PLUS FABRIC COTTON",
    "price": "1899 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/black1.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
  },
  {
    "id": 3,
    "title": "PRESTIGE FABRIC COTTON-LF",
    "price": "2399 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/black1.png",
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Cotton Fabric",
  },
  {
    "id": 4,
    "title": "VISION ARTISTIC FABRIC BLENDED-LF",
    "price": "2499 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/brown1.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 5,
    "title": "BABY PINK FABRIC DIP DYED YARN GL-04M",
    "price": "4999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/pink1 (1).png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 6,
    "title": "OFF WHITE PEACH FABRIC",
    "price": "3299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/white2.png",
    "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Cotton Fabric",
},
  {
    "id": 7,
    "title": "OPUS DUKE FABRIC BLENDED",
    "price": "2999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/pinkish2.png",
    "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Cotton Fabric",
},
  {
    "id": 8,
    "title": "GUL 900 IMPACT FABRIC BLENDED-LF",
    "price": "2399 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/lightbrown.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 9,
    "title": "KARANDI FABRIC KARANDI-LF",
    "price": "2999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/navyblue.png",
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Cotton Fabric",
},
  {
    "id": 10,
    "title": "HITEX SATIN PLUS FABRIC COTTON",
    "price": "5550 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/geeenshade.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 11,
    "title": "HITEX COOL FABRIC COTTON-LF",
    "price": "7850 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/darkgrey.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 12,
    "title": "CARNIVAL LATHA FABRIC COTTON-LF",
    "price": "5999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/nbrown.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 13,
    "title": "OPUS BRAVO FABRIC BLENDED",
    "price": "3599 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/darkbrown.png",
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Cotton Fabric",
},
  {
    "id": 14,
    "title": "VISION ARTISTIC FABRIC BLENDED-LF",
    "price": "2899 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/light.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 15,
    "title": "OPUS ICONIC FABRIC BLENDED-LF",
    "price": "2299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/lightblue.png",
    "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 16,
    "title": "GINI GOLD FABRIC BLENDED-LF",
    "price": "2599 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of GulAhmed Men’s Collection.",
    "brand": "Gul Ahmed",
    "image": "./images/gulahmed/shineblack.png",
    "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Cotton Fabric",
},



]
