var products = [{
    "id": 0,
    "title": "-- Select Anyone --",
    "price": "",
    "description": "",
    "brand": "",
    "image": "images/No_Image.png",
  },
// J. DATA 
  {
    "id": 1,
    "title": "BROWN COTTON KAMEEZ SHALWAR",
    "price": "2299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/1.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
  },
  {
    "id": 2,
    "title": "BROWN COTTON KAMEEZ SHALWAR",
    "price": "1899 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/2.png",
    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
  },
  {
    "id": 3,
    "title": "LIGHT BROWN COTTON KAMEEZ SHALWAR",
    "price": "2399 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/3.png",
    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Cotton Fabric",
  },
  {
    "id": 4,
    "title": "BLACK BLENDED KAMEEZ SHALWAR",
    "price": "2499 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/4.png",    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 5,
    "title": "BAKU - BROWN KAMEEZ SHALWAR",
    "price": "4999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/5.png",    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 6,
    "title": "MALAYSIA - BLUE KAMEEZ SHALWAR",
    "price": "3299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/6.png",    "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Cotton Fabric",
},
  {
    "id": 7,
    "title": "GREY BLENDED KAMEEZ SHALWAR",
    "price": "2999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/7.png",
        "size": "Large & Small & Medium",
    "arrival": "Yes",
    "material": "Cotton Fabric",
},
  {
    "id": 8,
    "title": "WHITE BLENDED KAMEEZ SHALWAR",
    "price": "2399 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/8.png",    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 9,
    "title": "ISFAHAN - GREEN KAMEEZ SHALWAR",
    "price": "2999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/9.png",    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Cotton Fabric",
},
  {
    "id": 10,
    "title": "BROWN COTTON KAMEEZ SHALWAR",
    "price": "5550 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/10.png",    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 11,
    "title": "WHITE KAMEEZ SHALWAR",
    "price": "7850 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/11.png",    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 12,
    "title": "DARK BROWN BLENDED KAMEEZ SHALWAR",
    "price": "5999 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/12.png",    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 13,
    "title": "MARLED BLUE BLENDED KAMEEZ SHALWAR",
    "price": "3599 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/13.png",    "size": "Large & Small",
    "arrival": "Yes",
    "material": "Cotton Fabric",
},
  {
    "id": 14,
    "title": "GREY BLENDED KAMEEZ SHALWAR",
    "price": "2899 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/14.png",    "size": "Large & Small",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 15,
    "title": "OPUS ICONIC FABRIC BLENDED-LF",
    "price": "2299 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/15.png",    "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Cotton Fabric",
},
  {
    "id": 16,
    "title": "GINI GOLD FABRIC BLENDED-LF",
    "price": "2599 PKR",
    "description": "Craft your wardrobe of essentials with the finest fabrics of junaid Jamshed J. Collection for Winters and Summers.",
    "brand": "Gul Ahmed",
    "image": "./images/j/16.png",
    "size": "Large & Small & Medium",
    "arrival": "No",
    "material": "Cotton Fabric",
},



]
